---
- name: Manage {{ terraform_demo_cloud_choice }} resources using a Terraform Plan
  hosts: all
  gather_facts: false
  vars:
    working_dir_name_choice: "provision_{{ terraform_demo_cloud_choice }}_resources"
    tf_plan_file_name_choice: "provision_{{ terraform_demo_cloud_choice }}_resources.tf"
    tf_vars_file_name_choice: "provision_{{ terraform_demo_cloud_choice }}_resources.tfvars"
    prepare_callback_demo: false
  roles:
  - rsoliman.terraform_demos.terraform_manage_resources