---
- name: Manage {{ terraform_demo_cloud_choice }} resources using a Terraform Plan
  hosts: all
  gather_facts: false
  vars:
    use_terraform_cloud: false
    working_dir_name_choice: "provision_{{  'tfcloud_' if (use_terraform_cloud is defined and use_terraform_cloud) else '' }}{{ terraform_demo_cloud_choice }}_resources"
    tf_plan_file_name_choice: "provision_{{  'tfcloud_' if (use_terraform_cloud is defined and use_terraform_cloud) else '' }}{{ terraform_demo_cloud_choice }}_resources.tf"
    tf_vars_file_name_choice: "provision_{{  'tfcloud_' if (use_terraform_cloud is defined and use_terraform_cloud) else '' }}{{ terraform_demo_cloud_choice }}_resources.tfvars"
    prepare_callback_demo: false
  roles:
  - rsoliman.terraform_demos.terraform_manage_resources