---
- name: Provision GCP resources using a Terraform Plan
  hosts: all
  gather_facts: false
  tasks:

  - name: Basic usage
    ansible.builtin.debug:
      msg: "'{{ lookup('ansible.builtin.env', 'AWS_ACCESS_KEY_ID') }}' is the HOME environment variable."

  - name: Basic usage
    ansible.builtin.debug:
      msg: "'{{ lookup('ansible.builtin.env', 'AWS_SECRET_ACCESS_KEY') }}' is the HOME environment variable."