---
- name: Manage {{ terraform_demo_cloud_choice }} resources using a Terraform Plan
  hosts: all
  gather_facts: false
  vars:
    use_terraform_cloud: true
    working_dir_name_choice: "provision_tfcloud_aws_resources"
    tf_plan_file_name_choice: "provision_tfcloud_aws_resources.tf" 
    prepare_callback_demo: false
  tasks:

  - name: Make sure working directory exists
    ansible.builtin.file:
      path: /var/terraform/plans/{{ working_dir_name }}
      state: directory
      mode: '0755'

  - name: Copy the TF Plan
    ansible.builtin.copy:
      src: "{{ tf_plan_file_name }}"
      dest: /var/terraform/plans/{{ working_dir_name }}/{{ tf_plan_file_name }}

  - name: TFCloud Only - config Terraform Cloud
    ansible.builtin.template:
      src: "terraformrc.j2"
      dest: ~/.terraformrc
    no_log: true
    when: use_terraform_cloud | bool

  - name: manage terraform plan
    cloud.terraform.terraform:
      force_init: false
      project_path: /var/terraform/plans/{{ working_dir_name }}
      state: "{{ resources_state }}"