---
# tasks file for terraform_provision_resources
- name: Make sure working directory exists
  ansible.builtin.file:
    path: /var/terraform/plans/{{ working_dir_name }}
    state: directory
    mode: '0755'

- name: Copy the TF Plan
  ansible.builtin.copy:
    src: "{{ tf_plan_file_name }}"
    dest: /var/terraform/plans/{{ working_dir_name }}/{{ tf_plan_file_name }}

- name: Copy the TF Vars Template
  ansible.builtin.template:
    src: "{{ tf_vars_file_name }}.j2"
    dest: /var/terraform/plans/{{ working_dir_name }}/{{ tf_vars_file_name }}

- name: Copy the userdata script for callbacks
  ansible.builtin.template:
    src: "{{ init_script_name }}.j2"
    dest: /var/terraform/plans/{{ working_dir_name }}/{{ init_script_name }}

- name: Apply terraform plan
  cloud.terraform.terraform:
    force_init: true
    lock: true
    project_path: /var/terraform/plans/{{ working_dir_name }}
    variables_file: /var/terraform/plans/{{ working_dir_name }}/{{ tf_vars_file_name }}
    state: present
  when: prepare_callback_demo is not defined or not prepare_callback_demo