---
# tasks file for terraform_provision_aws_resources
- name: destroy terraform plan
  cloud.terraform.terraform:
    project_path: /var/terraform/plans/{{ working_dir_name }}
    state: absent
    purge_workspace: yes
    variables_file: /var/terraform/plans/{{ working_dir_name }}/{{ tf_vars_file_name }}
    backend_config:
      region: "us-east-1"
      bucket: "tfdemo-backend-bucket"
      key: "aws/terraform.tfstate"

- name: Remove the /var/terraform/plans/{{ working_dir_name }} directory
  ansible.builtin.file:
    path: /var/terraform/plans/{{ working_dir_name }}
    state: absent

