---
# vars file for terraform_provision_aws_resources
working_dir_name: "{{ working_dir_name_choice | default('provision_aws_resources') }}"
tf_plan_file_name: "{{ tf_plan_file_name_choice | default('provision_aws_resources.tf') }}"
tf_vars_file_name: "{{ tf_vars_file_name_choice | default('provision_aws_resources.tfvars') }}"
#init_script_name: "{{ 'windows_startup_script.ps1' if virtualmachine_ostype_choice is defined and virtualmachine_ostype_choice == 'Windows' else 'userdata_Linux.sh' | default('userdata_Linux.sh') }}"
init_script_name: "{{ 'userdata_Linux.sh' | default('userdata_Linux.sh') }}"
resources_state: "{{ resources_state_choice | default('present') }}"

ansible_controller_url: controller.demo.com
ansible_controller_host_key: 123
ansible_controller_template_id: 1


azure_vm_os: "{{ azure_vm_os_choice | default('CentOS7.5') }}"
azure_instance_private_ip_address: "{{ azure_instance_private_ip_address_choice | default('10.0.1.100') }}"
azure_vm_image:
  CentOS7.5:
    image_publisher: "OpenLogic"
    image_offer: "CentOS"
    image_sku: "7.5"
    image_version: "latest"  
  CentOS7.7:
    image_publisher: "OpenLogic"
    image_offer: "CentOS"
    image_sku: "7.7"
    image_version: "latest"  
  RHEL7.8: 
    image_publisher: "RedHat"
    image_offer: "RHEL"
    image_sku: "7.8"
    image_version: "latest"
  RHEL8.2: 
    image_publisher: "RedHat"
    image_offer: "RHEL"
    image_sku: "8.2"
    image_version: "latest"  
  Ubuntu18.04LTS: 
    image_publisher: "Canonical"
    image_offer: "UbuntuServer"
    image_sku: "18.04-LTS"
    image_version: "latest"
