- name: manage terraform plan
  cloud.terraform.terraform:
    force_init: true
    lock: true
    project_path: /var/terraform/plans/{{ working_dir_name }}
    variables_file: /var/terraform/plans/{{ working_dir_name }}/{{ tf_vars_file_name }}
    state: "{{ resources_state }}"
  when: use_terraform_cloud is defined and use_terraform_cloud | bool

- name: manage terraform plan
  cloud.terraform.terraform:
    force_init: true
    lock: true
    project_path: /var/terraform/plans/{{ working_dir_name }}
    variables_file: /var/terraform/plans/{{ working_dir_name }}/{{ tf_vars_file_name }}
    state: "{{ resources_state }}"
    backend_config:
      region: "us-east-1"
      bucket: "foxhound-ansible-tfdemo-backend-bucket"
      key: "aws/terraform.tfstate"
  when: use_terraform_cloud is defined and not use_terraform_cloud | bool

  