---
# tasks file for terraform_provision_resources

- name: Make sure working directory exists
  ansible.builtin.file:
    path: /var/terraform/plans/{{ working_dir_name }}
    state: directory
    mode: '0755'

- name: Copy the TF Plan
  ansible.builtin.copy:
    src: "{{ tf_plan_file_name }}"
    dest: /var/terraform/plans/{{ working_dir_name }}/{{ tf_plan_file_name }}

- name: Copy the TF Vars Template
  ansible.builtin.template:
    src: "{{ tf_vars_file_name }}.j2"
    dest: /var/terraform/plans/{{ working_dir_name }}/{{ tf_vars_file_name }}

- name: Copy the userdata script for callbacks
  ansible.builtin.template:
    src: "{{ init_script_name }}.j2"
    dest: /var/terraform/plans/{{ working_dir_name }}/{{ init_script_name }}

- name: TFCloud Only - config Terraform Cloud
  ansible.builtin.template:
    src: "terraformrc.j2"
    dest: ~/.terraformrc
  no_log: true
  when: use_terraform_cloud | bool

- name: Include tasks for {{ terraform_demo_cloud }} management
  ansible.builtin.include_tasks: "{{ terraform_demo_cloud }}.yml"
  when: not prepare_callback_demo | bool