namespace: rsoliman
name: terraform_demos
version: 1.0.0
readme: README.md
authors:
- Raed Soliman <raedrizk@gmail.com>

description: A collection of roles used to demo driving Terraform plans using ansible to create and destroy resources on both AWS and Azure.

license:
- "MIT"

tags: ['terraform','demo','ansible','raedrizk','rsoliman']

dependencies:
    "community.general": "*"
    "ansible.builtin": "*"

repository: http://example.com/repository
homepage: http://example.com
issues: http://example.com/issue/tracker
